apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
  labels:
    app: helloworld
spec:
  containers:
  - name: nginx
    image: lasdjf
    ports:
    - name: nginxport
      containerPort: 80
